<?php

namespace PremiumKickBot\Commands;

use SergiX44\Nutgram\Nutgram;
use SergiX44\Nutgram\Telegram\Attributes\ParseMode;
use SergiX44\Nutgram\Telegram\Types\Keyboard\InlineKeyboardButton;
use SergiX44\Nutgram\Telegram\Types\Keyboard\InlineKeyboardMarkup;

class StartCommand
{

    public function __invoke(Nutgram $bot): void
    {
        $text = '*Hi, [%s](tg://user?id=%d)\!*


❓ __*HOW TO USE*__ ❓

To use me, you just need to *add me to any group or channel with the _"Invite users"_ permission\.* Then, *copy the invite link automatically generated by me* \(you\'ll find it in the "Invite link" section of your chat settings\)\.


➕ __*ADDITIONAL FEATURES \(only for groups\)*__ ➕

• 🗑 If you\'d like *to delete all new messages written by any premium user, just add the _"Delete messages"_ permission\.*
• ❌ If you\'d also like *to ban any premium user, just add the _"Restrict members"_ permission\.*

ℹ️ __*FAQ*__ ℹ️

_Q:_ The bot isn\'t working, it doesn\'t do anything\!
_A:_ The migration might have broken it, just remove it from your chat and add it again\.

_Q:_ Why did you make this bot?
_A:_ Actually, just for fun\. But if you find it useful, feel free to use it\!

_Q:_ I\'d like to contribute, what can I do?
_A:_ You can always open a pull request \(source code is [here](https://github.com/sys-001/PremiumKickBot)\), or you can just /donate\!

_Q:_ Which library are you using for this bot?
_A:_ Initially I wrote it in Python using [Pyrogram](https://pyrogram.org), but now I\'m using [Nutgram](https://nutgram.dev)\.

_Q:_ Can you make a bot for me?
_A:_ Sure\! Not for free though, sorry\.

_Q:_ Where can I follow your updates?
_A:_ I\'ve recently created a channel: take a look at @SysDevBlog\.';
        $name = $bot->user()?->first_name ?? $bot->user()?->username ?? $bot->userId() ?? 'user';
        $keyboard = InlineKeyboardMarkup::make();
        $keyboard->addRow(
            InlineKeyboardButton::make(
                '📢 Add to channel',
                url: sprintf('https://t.me/%s?startchannel&admin=invite_users', $_ENV['BOT_USERNAME'])
            ),
            InlineKeyboardButton::make(
                '👥 Add to group',
                url: sprintf('https://t.me/%s?startgroup&admin=invite_users', $_ENV['BOT_USERNAME'])
            )
        );
        $keyboard->addRow(
            InlineKeyboardButton::make('🧑‍💻 Author', url: 'https://t.me/sys001'),
            InlineKeyboardButton::make('🗄 Source code', url: 'https://github.com/sys-001/tg-premiumkickbot')
        );
        $keyboard->addRow(InlineKeyboardButton::make('⭐️ Rate me', url: 'https://t.me/BotsArchive/2443'));
        $bot->sendMessage(
            sprintf($text, $name, $bot->userId() ?? 0),
            ['parse_mode' => ParseMode::MARKDOWN, 'reply_markup' => $keyboard, 'disable_web_page_preview' => true]
        );
    }

}